author: Freed Creators
photosurl: /images/photos

permalink: /:categories/:title.html
excerpt_separator: <!--excerpt-->
gems: [jekyll-paginate]
paginate: 6
paginate_path: "/blog/page:num"
timezone: Asia/Shanghai
